services:
  taskmanager.api:
    image: alexdrdeveloper01/taskmanagerapi
    build:
      context: .
      dockerfile: src/Applications/TaskManager.Api/Dockerfile    
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ./src/Applications/TaskManager.Api/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
